### ISSUE TITLE
Searching for a word with only one occurrence with "*" no longer highlights that word

### ISSUE THREAD

**Issue by lins05** [emacs-evil/evil#1233]
After upgrading to the latest version of eveil, I noticed when a word has only one occurrence in a buffer, searching it with "*" would not highlight it. For example see the screenshot below when I try to search for the word "this":

**Before**

<img width="233" alt="Screen Shot 2019-12-30 at 8 43 41 PM" src="https://user-images.githubusercontent.com/717363/71582503-79894b00-2b45-11ea-83a7-66c487ffd640.png">

**After**

The word "this" is no longer highlighted.

---------------------------------

After using git-bisect it seems PR https://github.com/emacs-evil/evil/pull/1221 is the one that introduced this behavior. Is this a bug or expected?

**Comment by TheBB** [comment]
Probably a bug, might have to adjust the bounds in that PR.

**Comment by hlissner** [comment]
`(setq evil-ex-interactive-search-highlight 'all-windows)` gets around the problem for the time being.

**Comment by TheBB** [comment]
I know how to fix this, just need some time to get it right.

**Comment by TheBB** [comment]
#1235 reverts the problematic commit and fixes the original problem in a better way

**Comment by Alexander-Shukaev** [comment]
I like the previous change (#1221) more as it was less involved and intrusive into `isearch`.  The only reason why this issue exists now is because of how search `origin` is always taken starting from the next character, which would not hit the current match.  As a result, commands like `evil-search-word-forward` don't highlight the current match under point even when search wrapping is enabled in case this is the only match in the buffer (as per #1221).  Yes, they did highlight the current match under point before #1221 only when search wrapping was enabled, which to me is also weird behavior.  For myself, I fixed the current issue (while still retaining changes from #1221) by letting the `origin` start from the beginning of the current match (rather than from the next character), and only forcefully move `origin` to the next character when `evil-search-next` or `evil-search-previous` are used for search repetitions.

**Comment by TheBB** [comment]
@Alexander-Shukaev would you like to PR that change so I can see?

**Comment by TheBB** [comment]
As I understand it, your approach also would not fix the related issue (which is still present on master in fact) where you have two matches in different parts of the buffer, both of which are invisible.

**Comment by Alexander-Shukaev** [comment]
You're right, though the current issue is solved, the original one is still there for your example.  Sigh...  I guess we need your patch indeed, thanks for that.  :+1:

**Comment by hlissner** [comment]
It appears this issue hasn't been fixed. With the following in vanilla Emacs, `*` and `#` do not produce highlights when `evil-ex-interactive-search-highlight` is set to `'selected-window`:

```elisp
(require 'evil)
(evil-mode)
(setq evil-ex-interactive-search-highlight 'selected-window)
(evil-select-search-module 'evil-search-module 'evil-search)
```

**Comment by TheBB** [comment]
@hlissner That's a different bug. The problem here was not that it wasn't highlighted, but that it wasn't found at all. Could you report separately please?
